version: '3.8'

services:
  bot:
    image: "${BOT_IMAGE_NAME}"
    container_name: "${BOT_CONTAINER_NAME}"
    stop_signal: SIGINT
    build:
      context: .
    working_dir: "/usr/src/app/${BOT_NAME}"
    volumes:
      - .:/usr/src/app/${BOT_NAME}
      - postgres_volume:/root/postgres_volume
    command: python3 -m bot
    restart: always
    env_file:
      - ".env"
    networks:
      - tg_bot
    depends_on:
      - postgres
      # - redis
    stdin_open: true
    tty: true


  # redis:
  #   image: redis:6.2-alpine
  #   container_name: "${BOT_NAME}-redis"
  #   restart: always
  #   volumes:
  #     - redis_data:/data
  #   ports:
  #     - 6379:6379
  #   networks:
  #     - tg_bot


  postgres:
    image: postgres:15.1-alpine
    container_name: "${BOT_NAME}-postgres_db"
    restart: always
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - 5433:5432
    user: ${DB_USER}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    networks:
      - tg_bot


volumes:
  postgres_volume:
  # redis_data:


networks:
  tg_bot:
    driver: bridge